apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "dispatch-msg-ingest-service-deployment"
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 3
  template:
    metadata:
      labels:
        app: "dispatch-msg-ingest-service-selector"
    spec:
      hostAliases:
        - ip: "10.144.172.253"
          hostnames:
          - "scylla01.mil01.bat.cloud"    
      imagePullSecrets:
        - name: tpdservice-devops-image-pull-secret
      containers:
        - name: dispatch-msg-ingest-service
          image: gbs-bat-devops-preprod-docker-local.artifactory.swg-devops.com:443/dispatch-msg-ingest-service:latest
          env:
          - name: KAFKA_BROKER
            value: "kafka-0.kafka-headless.kafka-mil.svc.cluster.local:9092,kafka-1.kafka-headless.kafka-mil.svc.cluster.local:9092,kafka-2.kafka-headless.kafka-mil.svc.cluster.local:9092"
          - name: SCYLLA_DB
            value: "scylla01.mil01.bat.cloud"
          - name: SCYLLA_PORT
            value: "9042"            
          - name: SCYLLA_DB_USER_ID
            value: "kafcons"
          - name: SCYLLA_DB_PASSWORD
            value: "@%$lk*&we@45"            
          - name: kafka.producer.timeout.interval
            value: "100"
          - name: kafka.producer.retry.topic.max.retry.count
            value: "5"
          - name: debug.log.enabled
            value: "false"
          - name: business.validation.enabled
            value: "true"
          - name: nontpd.uid.stripping.enabled
            value: "false"
          - name: SCYLLA_TTL
            value: "1830"
          - name: PERFORM_HASH_VALIDATION
            value: "true"
          - name: SCYLLA_LOOKUP_KEYSPACE
            value: "bat_tpd_pri_msg"
          - name: implicit-disaggregation-enabled
            value: "true"
          - name: publish-history-enabled
            value: "true"
          - name: scylla-asyncWrite-batchSize
            value: "8000"
          - name: scylla-asyncWrite-timeout
            value: "10000"
          - name: gracePeriod-startDate
            value: "2020-02-23T00:00:00"                                  
          readinessProbe:
            httpGet:
             path: /greeting
             port: 8080
            initialDelaySeconds: 70
      nodeSelector:
        deployment: milan
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
